### ISSUE TITLE
Can it provide default templates for MELPA user?

### ISSUE THREAD

**Issue by stardiviner** [nbfalcon/ptemplate#1]
Now ptemplate is available on MELPA, hope this package can provide default templates so user can use it directly. It will be much helpful. WDYT?

**Comment by nbfalcon** [comment]
I agree! There already is a C/C++ project template, and I have just written one for Emacs Cask projects. I will be setting up a new repository for them very soon and will close this issue when that is done.

**Comment by stardiviner** [comment]
Wow! That's great, I'm curious how those templates can be downloaded from MELPA? Will it be a separate package or in current package?

**Comment by nbfalcon** [comment]
Actually, I don't know how to do it either right now, so I'll have to look at how yasnippet-snippets does it, but that won't be too much of an issue.

**Comment by nbfalcon** [comment]
Oh, and it will be a separate package.

**Comment by nbfalcon** [comment]
Done: https://github.com/nbfalcon/ptemplate-templates
I won't be closing this issue yet, as there are still some things to do: I should link to it in the README, remove the templates folder here, but you can already use them.

**Comment by stardiviner** [comment]
Thanks for quick great work!

**Comment by nbfalcon** [comment]
I think I'm done here: not only is this issue fixed, but ptemplate now supports every feature under the sun in a way that is not broken.

**Comment by nbfalcon** [comment]
MELPA integration is coming soon: see [this PR](https://github.com/melpa/melpa/pull/7194). The template collection could then simply be installed and configured using M-x package-install ptemplate-templates.

**Comment by stardiviner** [comment]
Awesome, glade to see it coming.

**Comment by nbfalcon** [comment]
The MELPA PR was merged, so you can now install `ptemplate-templates` from MELPA as usual (I'll address this in the README of that project shortly). Note the set-up instructions, because a config line has to be added for the templates become available.

**Comment by stardiviner** [comment]
Thanks for your working. @nbfalcon
